global:
  message: Welcome to order service dev environment
server:
  port: 8083
message: Hello from Order Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
